[tools]
python = "3.12"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.setup]
description = "Install Python dependencies"
run = """
python -m ensurepip --upgrade
python -m pip install -r requirements.txt
"""
